## Code for extracting Age and Gender related stats from Neighbourhood Profiles file.

#### Import Libraries and customize plotting settings

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

#### Set filename for Neighbourhood profiles and read into Pandas Dataframe

In [2]:
filename='2016_neighbourhood_profiles.csv'
df_raw= pd.read_csv(filename,header=0,encoding = "ISO-8859-1") #Note: Had to use encoding option to avoid errors

In [3]:
df_raw.head() # Check a few sample records

,Category,Topic,Data Source,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,...,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
0,Neighbourhood Information,Neighbourhood Information,City of Toronto,Neighbourhood Number,NaN,129,128,20,95,42,...,37,7,137,64,60,94,100,97,27,31
1,Neighbourhood Information,Neighbourhood Information,City of Toronto,TSNS2020 Designation,NaN,No Designation,No Designation,No Designation,No Designation,No Designation,...,No Designation,No Designation,NIA,No Designation,No Designation,No Designation,No Designation,No Designation,NIA,Emerging Neighbourhood
2,Population,Population and dwellings,Census Profile 98-316-X2016001,"Population, 2016","2,731,571","29,113","23,757","12,054","30,526","27,695",...,"16,936","22,156","53,485","12,541","7,865","14,349","11,817","12,528","27,593","14,804"
3,Population,Population and dwellings,Census Profile 98-316-X2016001,"Population, 2011","2,615,060","30,279","21,988","11,904","29,177","26,918",...,"15,004","21,343","53,350","11,703","7,826","13,986","10,578","11,652","27,713","14,687"
4,Population,Population and dwellings,Census Profile 98-316-X2016001,Population Change 2011-2016,4.50%,-3.90%,8.00%,1.30%,4.60%,2.90%,...,12.90%,3.80%,0.30%,7.20%,0.50%,2.60%,11.70%,7.50%,-0.40%,0.80%

#### Create a new analytics dataframe with relevant rows and columns for calculating Age and Sex related statistics.

In [4]:
df_analysis=df_raw.loc[(df_raw['Category']=='Population')  & (df_raw['Topic']=='Age characteristics') & ((df_raw['Characteristic'].str.contains('Male')) | (df_raw['Characteristic'].str.contains('Female'))),'Characteristic':]

In [5]:
df_analysis.describe()

,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,...,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
count,42,42,42,42,42,42,42,42,42,42,...,42,42,42,42,42,42,42,42,42,42
unique,42,42,37,37,36,39,33,37,38,39,...,37,34,41,36,35,34,36,39,38,36
top,Female: 0 to 04 years,"69,895",1015,975,515,25,730,415,0,0,...,290,545,1585,0,180,315,0,220,0,355
freq,1,1,2,2,2,2,2,2,3,2,...,2,3,2,4,2,3,3,2,3,2

#### Check for Missing Values

In [6]:
df_analysis[df_analysis.isnull().any(axis=1)]

Empty DataFrame
Columns: [Characteristic, City of Toronto, Agincourt North, Agincourt South-Malvern West, Alderwood, Annex, Banbury-Don Mills, Bathurst Manor, Bay Street Corridor, Bayview Village, Bayview Woods-Steeles, Bedford Park-Nortown, Beechborough-Greenbrook, Bendale, Birchcliffe-Cliffside, Black Creek, Blake-Jones, Briar Hill-Belgravia, Bridle Path-Sunnybrook-York Mills, Broadview North, Brookhaven-Amesbury, Cabbagetown-South St. James Town, Caledonia-Fairbank, Casa Loma, Centennial Scarborough, Church-Yonge Corridor, Clairlea-Birchmount, Clanton Park, Cliffcrest, Corso Italia-Davenport, Danforth, Danforth East York, Don Valley Village, Dorset Park, Dovercourt-Wallace Emerson-Junction, Downsview-Roding-CFB, Dufferin Grove, East End-Danforth, Edenbridge-Humber Valley, Eglinton East, Elms-Old Rexdale, Englemount-Lawrence, Eringate-Centennial-West Deane, Etobicoke West Mall, Flemingdon Park, Forest Hill North, Forest Hill South, Glenfield-Jane Heights, Greenwood-Coxwell, Guildwood, Henry Farm, High Park North, High Park-Swansea, Highland Creek, Hillcrest Village, Humber Heights-Westmount, Humber Summit, Humbermede, Humewood-Cedarvale, Ionview, Islington-City Centre West, Junction Area, Keelesdale-Eglinton West, Kennedy Park, Kensington-Chinatown, Kingsview Village-The Westway, Kingsway South, Lambton Baby Point, L'Amoreaux, Lansing-Westgate, Lawrence Park North, Lawrence Park South, Leaside-Bennington, Little Portugal, Long Branch, Malvern, Maple Leaf, Markland Wood, Milliken, Mimico (includes Humber Bay Shores), Morningside, Moss Park, Mount Dennis, Mount Olive-Silverstone-Jamestown, Mount Pleasant East, Mount Pleasant West, New Toronto, Newtonbrook East, Newtonbrook West, Niagara, North Riverdale, North St. James Town, Oakridge, Oakwood Village, O'Connor-Parkview, Old East York, Palmerston-Little Italy, Parkwoods-Donalda, Pelmo Park-Humberlea, Playter Estates-Danforth, ...]
Index: []

[0 rows x 142 columns]

In [7]:
df_analysis

,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,...,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
15,Male: 0 to 04 years,"69,895",660,575,360,445,570,435,470,455,...,355,620,1625,460,225,325,300,220,755,320
16,Male: 05 to 09 years,"69,350",695,540,270,365,660,355,230,395,...,310,625,1705,400,180,350,305,220,685,315
17,Male: 10 to 14 years,"64,945",660,460,225,325,675,415,130,410,...,265,610,1600,330,180,310,280,195,635,370
18,Male: 15 to 19 years,"74,240",840,780,285,465,715,490,585,520,...,415,680,1815,275,160,260,255,145,900,485
19,Male: 20 to 24 years,"97,415",1015,1000,355,1215,700,530,2485,735,...,705,705,2310,255,200,385,345,260,1615,500
20,Male: 25 to 29 years,"113,905",1015,1045,355,2080,645,465,2115,1075,...,790,655,2010,335,235,595,530,630,1545,465
21,Male: 30 to 34 years,"108,895",835,820,410,1610,735,485,1695,1040,...,780,570,1730,510,315,620,605,620,1105,425
22,Male: 35 to 39 years,"94,070",680,625,455,1055,735,580,1010,805,...,555,590,1585,565,340,535,450,410,875,430
23,Male: 40 to 44 years,"86,535",760,610,420,835,815,435,560,685,...,530,605,1585,545,295,425,395,365,775,395
24,Male: 45 to 49 years,"90,860",890,760,440,850,1010,535,500,605,...,470,745,1675,505,300,480,390,405,775,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Female: 55 to 59 years,"94,660",1165,915,485,915,1005,605,500,775,...,590,835,1790,465,315,435,360,440,890,510
48,Female: 60 to 64 years,"81,600",1070,795,400,940,895,470,425,660,...,565,670,1415,400,280,450,355,465,640,475
49,Female: 65 to 69 years,"70,180",985,690,325,950,955,415,445,585,...,510,685,1240,265,190,385,345,485,565,390
50,Female: 70 to 74 years,"51,285",690,450,210,700,790,275,320,440,...,390,500,1005,175,125,330,245,395,440,345
51,Female: 75 to 79 years,"43,430",575,405,180,565,730,280,250,355,...,365,545,910,135,115,315,125,300,410,355
52,Female: 80 to 84 years,"34,965",485,350,210,425,650,285,170,315,...,325,535,745,100,80,275,95,225,345,355
53,Female: 85 to 89 years,"25,135",350,205,130,345,615,265,135,230,...,255,370,430,90,50,335,70,160,140,290
54,Female: 90 to 94 years,"13,500",160,100,70,260,360,165,50,115,...,125,155,200,30,15,210,35,100,50,190
55,Female: 95 to 99 years,"3,475",60,20,5,90,105,45,5,25,...,25,20,50,0,10,85,0,40,10,45
56,Female: 100 years and over,650,10,0,5,25,20,10,0,0,...,10,10,15,0,5,20,0,5,0,10

#### Remove ',' from values and convert to numbers

In [8]:
df_analysis.loc[:,'City of Toronto':]=df_analysis.loc[:,'City of Toronto':].apply(lambda x: x.str.replace(',', ''))
df_analysis.loc[:,'City of Toronto':]=df_analysis.loc[:,'City of Toronto':].apply(pd.to_numeric)
df_analysis

,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,...,Willowdale West,Willowridge-Martingrove-Richview,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park
15,Male: 0 to 04 years,69895,660,575,360,445,570,435,470,455,...,355,620,1625,460,225,325,300,220,755,320
16,Male: 05 to 09 years,69350,695,540,270,365,660,355,230,395,...,310,625,1705,400,180,350,305,220,685,315
17,Male: 10 to 14 years,64945,660,460,225,325,675,415,130,410,...,265,610,1600,330,180,310,280,195,635,370
18,Male: 15 to 19 years,74240,840,780,285,465,715,490,585,520,...,415,680,1815,275,160,260,255,145,900,485
19,Male: 20 to 24 years,97415,1015,1000,355,1215,700,530,2485,735,...,705,705,2310,255,200,385,345,260,1615,500
20,Male: 25 to 29 years,113905,1015,1045,355,2080,645,465,2115,1075,...,790,655,2010,335,235,595,530,630,1545,465
21,Male: 30 to 34 years,108895,835,820,410,1610,735,485,1695,1040,...,780,570,1730,510,315,620,605,620,1105,425
22,Male: 35 to 39 years,94070,680,625,455,1055,735,580,1010,805,...,555,590,1585,565,340,535,450,410,875,430
23,Male: 40 to 44 years,86535,760,610,420,835,815,435,560,685,...,530,605,1585,545,295,425,395,365,775,395
24,Male: 45 to 49 years,90860,890,760,440,850,1010,535,500,605,...,470,745,1675,505,300,480,390,405,775,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Female: 55 to 59 years,94660,1165,915,485,915,1005,605,500,775,...,590,835,1790,465,315,435,360,440,890,510
48,Female: 60 to 64 years,81600,1070,795,400,940,895,470,425,660,...,565,670,1415,400,280,450,355,465,640,475
49,Female: 65 to 69 years,70180,985,690,325,950,955,415,445,585,...,510,685,1240,265,190,385,345,485,565,390
50,Female: 70 to 74 years,51285,690,450,210,700,790,275,320,440,...,390,500,1005,175,125,330,245,395,440,345
51,Female: 75 to 79 years,43430,575,405,180,565,730,280,250,355,...,365,545,910,135,115,315,125,300,410,355
52,Female: 80 to 84 years,34965,485,350,210,425,650,285,170,315,...,325,535,745,100,80,275,95,225,345,355
53,Female: 85 to 89 years,25135,350,205,130,345,615,265,135,230,...,255,370,430,90,50,335,70,160,140,290
54,Female: 90 to 94 years,13500,160,100,70,260,360,165,50,115,...,125,155,200,30,15,210,35,100,50,190
55,Female: 95 to 99 years,3475,60,20,5,90,105,45,5,25,...,25,20,50,0,10,85,0,40,10,45
56,Female: 100 years and over,650,10,0,5,25,20,10,0,0,...,10,10,15,0,5,20,0,5,0,10

#### Engineer new Categories: 'Sex' and 'Age Group'

In [9]:
df_analysis.loc[df_analysis['Characteristic'].str.contains('Male'),'Sex']='Male'
df_analysis.loc[df_analysis['Characteristic'].str.contains('Female'),'Sex']='Female'
df_analysis['Age Group'] =''
for i in range(0,10):  
    df_analysis.loc[(df_analysis['Characteristic'].str.contains(str(i) + '4')) | (df_analysis['Characteristic'].str.contains(str(i) +'9')), 'Age Group'] = str(10*i) + ' to ' + str(i) + '9'

df_analysis.loc[df_analysis['Characteristic'].str.contains('100'),'Age Group']='100 and above'

In [10]:
df_analysis

,Characteristic,City of Toronto,Agincourt North,Agincourt South-Malvern West,Alderwood,Annex,Banbury-Don Mills,Bathurst Manor,Bay Street Corridor,Bayview Village,...,Woburn,Woodbine Corridor,Woodbine-Lumsden,Wychwood,Yonge-Eglinton,Yonge-St.Clair,York University Heights,Yorkdale-Glen Park,Sex,Age Group
15,Male: 0 to 04 years,69895,660,575,360,445,570,435,470,455,...,1625,460,225,325,300,220,755,320,Male,0 to 09
16,Male: 05 to 09 years,69350,695,540,270,365,660,355,230,395,...,1705,400,180,350,305,220,685,315,Male,0 to 09
17,Male: 10 to 14 years,64945,660,460,225,325,675,415,130,410,...,1600,330,180,310,280,195,635,370,Male,10 to 19
18,Male: 15 to 19 years,74240,840,780,285,465,715,490,585,520,...,1815,275,160,260,255,145,900,485,Male,10 to 19
19,Male: 20 to 24 years,97415,1015,1000,355,1215,700,530,2485,735,...,2310,255,200,385,345,260,1615,500,Male,20 to 29
20,Male: 25 to 29 years,113905,1015,1045,355,2080,645,465,2115,1075,...,2010,335,235,595,530,630,1545,465,Male,20 to 29
21,Male: 30 to 34 years,108895,835,820,410,1610,735,485,1695,1040,...,1730,510,315,620,605,620,1105,425,Male,30 to 39
22,Male: 35 to 39 years,94070,680,625,455,1055,735,580,1010,805,...,1585,565,340,535,450,410,875,430,Male,30 to 39
23,Male: 40 to 44 years,86535,760,610,420,835,815,435,560,685,...,1585,545,295,425,395,365,775,395,Male,40 to 49
24,Male: 45 to 49 years,90860,890,760,440,850,1010,535,500,605,...,1675,505,300,480,390,405,775,505,Male,40 to 49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,Female: 55 to 59 years,94660,1165,915,485,915,1005,605,500,775,...,1790,465,315,435,360,440,890,510,Female,50 to 59
48,Female: 60 to 64 years,81600,1070,795,400,940,895,470,425,660,...,1415,400,280,450,355,465,640,475,Female,60 to 69
49,Female: 65 to 69 years,70180,985,690,325,950,955,415,445,585,...,1240,265,190,385,345,485,565,390,Female,60 to 69
50,Female: 70 to 74 years,51285,690,450,210,700,790,275,320,440,...,1005,175,125,330,245,395,440,345,Female,70 to 79
51,Female: 75 to 79 years,43430,575,405,180,565,730,280,250,355,...,910,135,115,315,125,300,410,355,Female,70 to 79
52,Female: 80 to 84 years,34965,485,350,210,425,650,285,170,315,...,745,100,80,275,95,225,345,355,Female,80 to 89
53,Female: 85 to 89 years,25135,350,205,130,345,615,265,135,230,...,430,90,50,335,70,160,140,290,Female,80 to 89
54,Female: 90 to 94 years,13500,160,100,70,260,360,165,50,115,...,200,30,15,210,35,100,50,190,Female,90 to 99
55,Female: 95 to 99 years,3475,60,20,5,90,105,45,5,25,...,50,0,10,85,0,40,10,45,Female,90 to 99
56,Female: 100 years and over,650,10,0,5,25,20,10,0,0,...,15,0,5,20,0,5,0,10,Female,100 and above

#### Create final transposed version for Age analysis

In [12]:
df_age_analysis=df_analysis.copy()
df_age_analysis.drop(['Characteristic','Sex'],axis=1,inplace=True)

df_age_analysis=df_age_analysis.groupby('Age Group').sum().reindex(['0 to 09', '10 to 19','20 to 29', '30 to 39',
       '40 to 49', '50 to 59', '60 to 69', '70 to 79', '80 to 89', '90 to 99','100 and above']).T
df_age_analysis.index.name='Neighbourhood'

df_age_analysis

Age Group,0 to 09,10 to 19,20 to 29,30 to 39,40 to 49,50 to 59,60 to 69,70 to 79,80 to 89,90 to 99,100 and above
Neighbourhood,,,,,,,,,,,
City of Toronto,271030,272635,427690,420880,373320,385210,284410,169765,101435,24440,775
Agincourt North,2595,2960,4010,3225,3620,4675,3905,2345,1425,345,10
Agincourt South-Malvern West,2140,2405,3915,2995,3000,3710,2825,1630,950,185,0
Alderwood,1275,1055,1370,1745,1735,2055,1415,750,510,120,5
Annex,1690,1695,7080,5380,3455,3625,3425,2390,1335,455,30
Banbury-Don Mills,2330,2650,2740,3225,3970,4160,3295,2595,2040,660,25
Bathurst Manor,1555,1640,1985,2255,2195,2405,1650,980,825,310,15
Bay Street Corridor,1435,1610,10045,5175,2145,2180,1540,1055,535,90,0
Bayview Village,1660,1705,3770,3875,2830,2705,2275,1405,925,225,0
Bayview Woods-Steeles,915,1340,1695,1110,1620,1925,1775,1425,1015,310,10
...,...,...,...,...,...,...,...,...,...,...,...
Willowdale West,1295,1315,3020,2680,2055,2165,1940,1280,930,240,15
Willowridge-Martingrove-Richview,2395,2425,2605,2535,2785,3200,2545,1855,1530,265,10
Woburn,6510,6535,8330,7230,6890,7215,4990,3360,2090,385,15
Woodbine Corridor,1725,1140,1235,2235,2185,1925,1245,535,295,50,0
Woodbine-Lumsden,835,630,845,1375,1250,1290,915,450,220,35,5
Wychwood,1295,1075,2085,2285,1945,1715,1515,1070,970,380,20
Yonge-Eglinton,1230,1080,1960,2150,1685,1450,1270,655,275,60,0
Yonge-St.Clair,870,660,1990,2165,1615,1525,1615,1230,660,185,5
York University Heights,2780,3005,5835,4060,3375,3780,2275,1500,875,95,0
Yorkdale-Glen Park,1245,1630,1945,1830,1960,2060,1555,1205,1050,315,10

#### Create final transposed version for gender analysis

In [13]:
df_sex_analysis=df_analysis.copy()
df_sex_analysis.drop(['Characteristic','Age Group'],axis=1,inplace=True)
df_sex_analysis=df_sex_analysis.groupby(by='Sex').sum().T
df_sex_analysis

Sex                                Female     Male
City of Toronto                   1417995  1313595
Agincourt North                     15200    13915
Agincourt South-Malvern West        12145    11610
Alderwood                            6140     5895
Annex                               16205    14355
Banbury-Don Mills                   14895    12795
Bathurst Manor                       8350     7465
Bay Street Corridor                 13595    12215
Bayview Village                     11365    10010
Bayview Woods-Steeles                7125     6015
...                                   ...      ...
Willowdale West                      8960     7975
Willowridge-Martingrove-Richview    11520    10630
Woburn                              27540    26010
Woodbine Corridor                    6520     6050
Woodbine-Lumsden                     4040     3810
Wychwood                             7715     6640
Yonge-Eglinton                       6300     5515
Yonge-St.Clair                       6875     5645
York University Heights             13955    13625
Yorkdale-Glen Park                   7945     6860

[141 rows x 2 columns]